name: flash-merchant-signup
static_sites:
- name: web
  github:
    branch: gh-pages # Changed to gh-pages from which we deploy
    deploy_on_push: true
    repo: your-github-org/merchant-signup # Update this with your actual GitHub repo
  output_dir: / # Root directory since it's already processed by GitHub Actions
  routes:
  - path: /
  # No environment variables needed here - they're embedded at build time
  error_document: 404.html