name: flash-merchant-signup
static_sites:
- name: web
  github:
    branch: gh-pages # Use gh-pages branch containing the static build
    deploy_on_push: true
    repo: your-github-org/merchant-signup # Update this with your actual GitHub repo
  source_dir: / # Root directory of the gh-pages branch
  output_dir: / # Root directory since it's already processed
  build_command: "" # No build command needed - files are already built
  routes:
  - path: /
  cors:
    allow_origins:
    - regex: ".*"
  catchall_document: index.html # Use index.html for SPA routing
  error_document: 404.html
  env: []  # No environment variables - they're embedded in the static build