name: Check Pending Notifications

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  check-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Notification Function
        run: |
          curl -X POST "https://uygbqnrqwjvzdfbqeipf.functions.supabase.co/new-signup-email" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{}"
