name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "example-key-for-testing-only"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "example-maps-key-for-testing-only"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm test