name: Build and Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run environment checks
      run: node scripts/check-env.js
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      
    - name: Build Next.js app (static export)
      run: |
        npm run check-build-env
        npm run build:static:ci
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        IS_BUILD_TIME: "true"
        
    - name: List built files
      run: |
        echo "Static export structure:"
        ls -la out/ || echo "No 'out' directory found"
        
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Upload static build to GitHub Pages branch
      run: |
        # Setup git user
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Create a new orphan branch for GitHub Pages
        echo "Creating GitHub Pages branch with static output..."
        git checkout --orphan gh-pages
        
        # Remove all files except the output directory
        find . -maxdepth 1 ! -name "out" ! -name ".git" -exec rm -rf {} \;
        
        # Move output directory contents to the root and prepare for commit
        mv out/* .
        rm -rf out
        
        # Add and commit the static files
        git add .
        git commit -m "Deploy static site to GitHub Pages"
        
        # Force push to the gh-pages branch
        git push -f origin gh-pages
        
        echo "Deployed to GitHub Pages!"
        echo "To make this work with DigitalOcean, configure your app to deploy from the gh-pages branch"