name: Build and Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run environment checks
      run: node scripts/check-env.js
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      
    - name: Build Next.js app (static export)
      run: |
        npm run check-build-env
        npm run build:static:ci
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        IS_BUILD_TIME: "true"
        
    - name: List built files
      run: |
        echo "Static export structure:"
        ls -la out/ || echo "No 'out' directory found"
        
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Verify static output
      run: |
        echo "Verifying static export content..."
        ls -la out/
        if [ -f "out/index.html" ]; then
          echo "✅ index.html exists"
        else
          echo "❌ index.html is missing!"
          exit 1
        fi
        # Check if form directory exists, but don't fail if it's missing
        # (it might be in a different structure depending on Next.js export format)
        if [ -f "out/form/index.html" ]; then
          echo "✅ form/index.html exists"
        elif [ -f "out/form.html" ]; then
          echo "✅ form.html exists"
        else
          echo "⚠️ form page not found in expected locations, but continuing anyway"
        fi
        echo "✅ Static export verification complete"
        
    - name: Upload static build to GitHub Pages branch
      run: |
        # Setup git user
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Check if the gh-pages branch exists remotely
        if git ls-remote --heads origin gh-pages | grep -q 'gh-pages'; then
          echo "gh-pages branch exists, fetching it..."
          git fetch origin gh-pages
        fi
        
        # Create a new orphan branch for GitHub Pages
        echo "Creating GitHub Pages branch with static output..."
        git checkout --orphan gh-pages-new
        
        # Clear the working directory
        git rm -rf .
        
        # Copy the output directory contents
        echo "Copying static build files..."
        cp -r out/* .
        
        # Make sure we have a .nojekyll file to prevent GitHub Pages from trying to process the site with Jekyll
        touch .nojekyll
        
        # Add README.md to explain this branch
        echo "# Flash Merchant Signup - Static Build" > README.md
        echo "" >> README.md
        echo "This branch contains the static build of the Flash Merchant Signup application." >> README.md
        echo "It is generated automatically by GitHub Actions and is intended to be deployed to DigitalOcean App Platform." >> README.md
        echo "" >> README.md
        echo "The source code is in the \`main\` branch." >> README.md
        echo "" >> README.md
        echo "## Build Information" >> README.md
        echo "- Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> README.md
        echo "- Build Commit: $GITHUB_SHA" >> README.md
        
        # Add and commit the static files
        git add .
        git commit -m "Deploy static site to GitHub Pages ($(date -u +"%Y-%m-%d %H:%M:%S UTC"))"
        
        # Force push to the gh-pages branch
        echo "Pushing to gh-pages branch..."
        git push -f origin gh-pages-new:gh-pages
        
        # Go back to main branch
        git checkout main
        
        echo "✅ Deployed to GitHub Pages!"
        echo "The gh-pages branch now contains the latest static build"
        echo "To make this work with DigitalOcean, configure your app to deploy from the gh-pages branch"